### ISSUE TITLE
Using the library within a Parallel.ForEachAsync loop causes the error  TryStartNoGCRegion 'The NoGCRegion mode was already in progress'

### ISSUE THREAD

**Issue by Daniel-SchaeferJ** [gregyjames/OctaneDownloader#107]
**Describe the bug**
When Calling the following code 
```
Parallel.ForEachAsync ()
{
                var optimalNumberOfParts = Engine.GetOptimalNumberOfParts(blobInfo.PreSignedUrl).Result;
                var octaneEngine = new Engine(_loggerFactory, new OctaneConfiguration()
                {
                    Parts = optimalNumberOfParts,
                    NumRetries = 5,
                    
                });
                await octaneEngine.DownloadFile(blobInfo.PreSignedUrl,Path.Combine(_path, blobInfo.FilePath));
}
```
 TryStartNoGCRegion 'The NoGCRegion mode was already in progress is thrown
**To Reproduce**
Run above code with inputs of your choice

**Expected behavior**
I should be able to download multiple files in parallel

**Desktop (please complete the following information):**
Windoes 11 event dotnet 7

**Comment by Daniel-SchaeferJ** [comment]
And of course increasing the buffer size seems to throw the thing off when downloading

**Comment by gregyjames** [comment]
This issue has now been resolved. Please update to v6.0.1. Can you please open a seperate ticket for the buffer size issue?
