### ISSUE TITLE
Bug on the EngineBuilder with OctaneConfiguration as param

### ISSUE THREAD

**Issue by barbarian1803** [gregyjames/OctaneDownloader#121]
https://github.com/gregyjames/OctaneDownloader/blob/03e63b56c51bd24b01b2793c7e4ff2f176f64125/OctaneEngine/EngineBuilder.cs#L39

Line above, it register OctaneConfiguration object as IConfiguration. It will throw error.

**Comment by gregyjames** [comment]
Thanks for the catch, this has been resolved in v8.0.1 by using an in memory collection to take the values from the Octane Configuration object to build IConfiguration to register.

**Comment by barbarian1803** [comment]
Since in the AddOctane method we have this line:

https://github.com/gregyjames/OctaneDownloader/blob/8f5c763eeaf9bd91b5302f85aa2ed7200957b30b/OctaneEngine/ContainerBuilderExtensions.cs#L17

You can actually register OctaneConfiguration instead of creating IConfiguration.
This way, I can pass DoneCallback and ProgressCallback.

Creating IConfiguraition will prevent the DoneCallback and ProgressCallback to be passed correctly.

**Comment by gregyjames** [comment]
I think I will do extension methods on the engine object itself. To configure progress, done and proxy. I'm starting to think it shouldn't be in the config since you can't really serialize it. And it would be easier to modify down the line than using OctaneConfiguration.
