### ISSUE TITLE
Code examples in README would be nice

### ISSUE THREAD

**Issue by Morasiu** [gregyjames/OctaneDownloader#36]
**Is your feature request related to a problem? Please describe.**
As a new user, I would like to see some code examples in the README file.

**Describe the solution you'd like**
Add a simple code example and later in README a more complicated example.

**Describe alternatives you've considered**
Alternative a Wiki would be nice.

**Additional context**
See [this](https://github.com/Morasiu/Swashbuckle.AspNetCore.JsonMultipartFormDataSupport) as example README

**Comment by gregyjames** [comment]
Hello, this issue is being marked as resolved. I added the example from the test program to the readme.
