### ISSUE TITLE
Extend Engine to have Pause, Resume, Cancel operations

### ISSUE THREAD

**Issue by Pete-PlaytimeSolutions** [gregyjames/OctaneDownloader#68]
**Is your feature request related to a problem? Please describe.**
When dealing with large files, it would be good to be able to have to ability to Pause/Continue or Cancel the download.

**Describe the solution you'd like**
Add some additional methods to the Engine to Pause, Continue and Cancel the download process.

**Describe alternatives you've considered**
Another suggestion would also be to not implement the Engine as a static class, that way you could support the ability to have multiple concurrent downloads happening at once.

**Comment by gregyjames** [comment]
This issue is now resolved. Thank you for the suggestion. I will look into making the Engine non static at a later date, but for now, pause/resume/cancellation support has been added.
