### ISSUE TITLE
The ProgressCallback is never called

### ISSUE THREAD

**Issue by remygrandin** [gregyjames/OctaneDownloader#69]
**Describe the bug**
The ProgressCallback is never called

**To Reproduce**
- Load the test project
- set up a breakpoint in the ProgressCallback lambda
- Run the test project

**Expected behavior**
The ProgressCallback should be called

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows

**Additional context**
I can't find any trace of the calling code for ProgressCallback in the repo

**Comment by gregyjames** [comment]
This was accidental removed during refactoring, working on this now!

**Comment by gregyjames** [comment]
This issue should now be resolved.
