### ISSUE TITLE
Download the same file from multiple sources

### ISSUE THREAD

**Issue by notcaremath** [gregyjames/OctaneDownloader#84]
I want to download the same file from multiple sites to speed up the download as much as possible

**Comment by gregyjames** [comment]
Can you give an example of such a file? And some of the urls for testing?

**Comment by notcaremath** [comment]
比如说，将一个大文件（压缩文件，等等）放到两个或多个文件服务器上，当下载的时候，可以从服务器上分任务下载，类似于bt一样，从多个共享拉去同一个文件，这样提高下载速度。
